name: Enterprise CI/CD Pipeline

on:
  push:
    branches: [ main, release, prod ]

jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Install
      run: npm install

    - name: Load Environment
      run: bash scripts/load-env.sh

    - name: Test
      run: npm run test

    - name: Build
      run: npm run build

  deploy-stage:
    if: github.ref == 'refs/heads/main'
    needs: build-test
    runs-on: ubuntu-latest
    environment: stage

    steps:
    - uses: actions/checkout@v4
    - run: echo "Deploying to STAGE"

  deploy-beta:
    if: github.ref == 'refs/heads/release'
    needs: build-test
    runs-on: ubuntu-latest
    environment: beta

    steps:
    - uses: actions/checkout@v4
    - run: echo "Deploying to BETA"

  deploy-production:
    if: github.ref == 'refs/heads/prod'
    needs: build-test
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4
    - run: echo "Deploying to PRODUCTION"
